name: "lint-and-test"

on: ['push']

jobs:
  lint-and-test:
    name: "lint-and-test"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup node 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node dependencies
        run: yarn install

      - name: "Lint"
        run: yarn run lint

      - name: "Unit Test"
        run: yarn run test:unit